import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'Git & GitHub Practice',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	
	return (
		<html lang='ru'>
			<body>{children}</body>
		</html>
	);
}
